# -*- coding: utf-8 -*-
"""Caption

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhnelgVYszbPrD00edwBHKKLf3WbNYOJ
"""

# Commented out IPython magic to ensure Python compatibility.
from sentence_transformers import SentenceTransformer
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline
model = SentenceTransformer('clip-ViT-B-32')

text_description = ["Two dogs in the snow",
                    "A cat on a table",
                    "A picture of london at night",
                    "Taj Mahal View",
                    "A dog sleeping on a couch",
                    "Two cats fighting in the garden",
                    "kashmir is a beautiful place",
                    "edinburg castle is historical place",
                    "eiffel tower is a paris",
                    "New Zealand is a Amazing Country",
                    "Australia is a beatiful places in a country"]

def display_image_and_compare(image_path,text_description):
  img = Image.open(image_path)

  text_emb = model.encode(text_description)
  img_emb = model.encode(img)

  similarity_score = np.dot(text_emb,img_emb.T)

  best_match_index = np.argmax(similarity_score)
  best_match_desc = text_description[best_match_index]

  print(f"\nBest match for the image is L {best_match_desc} with score of {similarity_score.max()}")

  plt.figure(figsize=(6,6))
  plt.imshow(img)
  plt.axis('off')
  plt.title('Image for similarity comparison',fontsize=14)
  plt.show()

display_image_and_compare("/content/5.jpeg",  text_description)

display_image_and_compare("/content/6.jpeg",  text_description)

display_image_and_compare("/content/7.jpeg",  text_description)

display_image_and_compare("/content/8.jpeg",  text_description)

display_image_and_compare("/content/9.jpeg",  text_description)

display_image_and_compare("/content/10.jpeg",  text_description)

